# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024
# SPDX-FileContributor: Antonio Niño Díaz, 2024

name: Packages

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  build-linux:
    name: Build Pacman packages (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #arch: [x86_64, aarch64]
        arch: [x86_64]
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.20
          arch: ${{ matrix.arch }}
          packages: >
            build-base
            fakeroot
            git
            curl
            bash
            libarchive-tools
            xz
            zstd
            sudo
            coreutils
            sed
            patchelf

      # This folder needs to be created as root, but regular users need to be
      # able to modify it.
      - name: Create /opt/wonderful folder
        run: |
          sudo sh -c "mkdir /opt/wonderful && chown -R runner /opt/wonderful"
        shell: alpine.sh --root {0}

      - name: Install Wonderful
        run: |
          cd /opt/wonderful
          curl https://wonderful.asie.pl/bootstrap/wf-bootstrap-${{ matrix.arch }}.tar.gz | tar xzvf -
        shell: alpine.sh {0}

      - name: Install prerequisites (Wonderful)
        run: |
          export PATH=/opt/wonderful/bin:$PATH

          wf-pacman -Syu --noconfirm wonderful-base runtime-musl-dev
        shell: alpine.sh {0}

      # FIXME: The first launch of fakeroot via wf-makepkg seems to emit a
      # SIGUSR1 in this environment.  Thankfully, executing it again picks up
      # right where it left off.
      - name: Build packages
        run: |
          export PATH=/opt/wonderful/bin:$PATH
          export BLOCKSDS=/opt/wonderful/thirdparty/blocksds/core/
          export BLOCKSDSEXT=/opt/wonderful/thirdparty/blocksds/external/

          bash ./build.sh --install --retry
        shell: alpine.sh {0}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pacman packages (Linux, ${{ matrix.arch }})
          path: ${{ github.workspace }}/*/*.pkg.tar.xz
